spring.application.name=4-Arcade-backend

spring.config.import=optional:file:.env[.properties]

# postgresql db setting
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USERNAME}
spring.datasource.password=${DATASOURCE_PASSWORD}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.schemas=public

# JPA setting
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true

#debug=true